steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/gitops-test-1', '.']

  # Push the container image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gitops-test-1']

  # Set up authentication to GKE
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'container',
        'clusters',
        'get-credentials',
        'gitops-test-1',
        '--zone=us-central1-a',
        '--project=$PROJECT_ID'
      ]

  # Deploy to GKE using kubectl
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      [
        'apply',
        '-f',
        'gke.yaml'
      ]

options:
  logging: NONE
